workflows:
  test-and-deploy:
    jobs:
      - node/test
      - build-and-deploy:
        requires:
          - node/test      
      executor: node/default
      steps:
        - checkout
        - node/install-packages
      - run:
        name: Build
        command: npm run build
      - run:
        name: Deploy Netlify
        command: npx netlify deploy --prod --dir=build
